apiVersion: v1
kind: Secret
metadata:
  name: crms-secret
  namespace: crms-backend
type: Opaque
stringData:
  DATABASE_URL: "postgres://user:REPLACE_ME_PASSWORD@db-host:5432/crmsdb"
  JWT_SECRET: "REPLACE_ME_JWT_SECRET"
